import type { Application } from "./types";

const sampleApplications: Application[] = [
  {
    id: 1,
    company: "TCS",
    jobTitle: "React Developer",
    location: "Pune",
    appliedDate: "29092026",
    status: "Applied",
    jobLink: "https://google.com",
    notes: "Applied through company website.",
  },
  {
    id: 2,
    company: "Infosys",
    jobTitle: "React Developer",
    location: "Bengaluru",
    appliedDate: "27092026",
    status: "Interview",
    jobLink: "https://google.com",
    notes: "Technical round on Monday. Revise hooks and JavaScript basics.",
  },
  {
    id: 3,
    company: "Wipro",
    jobTitle: "Frontend Developer",
    location: "Hyderabad",
    appliedDate: "24092026",
    status: "Applied",
    jobLink: "https://google.com",
    notes: "",
  },
  {
    id: 4,
    company: "Zoho",
    jobTitle: "UI Developer",
    location: "Chennai",
    appliedDate: "20092026",
    status: "Selected",
    jobLink: "https://google.com",
    notes: "Offer received. Joining date to be confirmed.",
  },
  {
    id: 5,
    company: "Capgemini",
    jobTitle: "React Frontend Developer",
    location: "Mumbai",
    appliedDate: "18092026",
    status: "Rejected",
    jobLink: "",
    notes: "Rejected after the first round. Practise more DSA.",
  },
  {
    id: 6,
    company: "Freshworks",
    jobTitle: "Junior Web Developer",
    location: "Remote",
    appliedDate: "15092026",
    status: "Interview",
    jobLink: "https://google.com",
    notes: "HR call done. Waiting for the technical round.",
  },
  {
    id: 7,
    company: "Accenture",
    jobTitle: "Software Engineer",
    location: "Pune",
    appliedDate: "12092026",
    status: "Applied",
    jobLink: "https://google.com",
    notes: "Applied through referral.",
  },
  {
    id: 8,
    company: "Cognizant",
    jobTitle: "React Developer",
    location: "Kolkata",
    appliedDate: "10092026",
    status: "Rejected",
    jobLink: "https://google.com",
    notes: "",
  },
  {
    id: 9,
    company: "Tech Mahindra",
    jobTitle: "Frontend Engineer",
    location: "Noida",
    appliedDate: "08092026",
    status: "Applied",
    jobLink: "",
    notes: "Found on LinkedIn.",
  },
  {
    id: 10,
    company: "Startup Studio",
    jobTitle: "React Intern",
    location: "Remote",
    appliedDate: "05092026",
    status: "Applied",
    jobLink: "https://google.com",
    notes: "Small startup. Asked for portfolio link.",
  },
];

export default sampleApplications;
